DROP TABLE IF EXISTS Utente
DROP TABLE IF EXISTS Libro
DROP TABLE IF EXISTS Prestito

CREATE TABLE Utente(
	utenteID INT PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(250) NOT NULL,
	cognome VARCHAR(250) NOT NULL,
	email VARCHAR(250) NOT NULL
);

CREATE TABLE Libro(
	libroID INT PRIMARY KEY IDENTITY(1,1),
	titolo VARCHAR(250) NOT NULL,
	annoPubblicazione DATE NOT NULL,
	isDisponibile BIT NOT NULL
);

CREATE TABLE Prestito(
	prestitoID INT PRIMARY KEY IDENTITY(1,1),
	dataPrestito DATE NOT NULL,
	dataRitorno DATE NOT NULL,
	utenteRIF INT NOT NULL,
	libroRIF INT NOT NULL,
	FOREIGN KEY (utenteRIF) REFERENCES Utente(utenteID) ON DELETE CASCADE,
	FOREIGN KEY (utenteRIF) REFERENCES Libro(libroID) ON DELETE CASCADE
);